### ISSUE TITLE
How can i receive Messages in voip? Objective c - Some Error !

### ISSUE THREAD

**Issue by 007fred50** [hasyapanchasara/PushKit_SilentPushNotification#4]
Hello,

Then i use  [This here in your github](https://github.com/hasyapanchasara/PushKit_SilentPushNotification)

i got alot of error see it here [Youtube video here](https://www.youtube.com/watch?v=6-4F-swWCR0)

my question is how i can send "silent push notification" over voip?

Frederik L. Frandsen

**Comment by hasyapanchasara** [comment]
Hi Fredrick,

I just saw your message here.

I have checked your video. Code which you are using from my repo is Swift language.

I hope you are using compatible Xcode version. 

Lastly I have updated code with swift 4, so you should use Xcode 9.2.
