### ISSUE TITLE
unable to connect to ssl://gateway.push.apple.com:2195 

### ISSUE THREAD

**Issue by Hamza123Imran** [hasyapanchasara/PushKit_SilentPushNotification#5]
Hi, i have followed all the steps properly and added everything as said in docs. But when i try to send notification from my backend i got this error, `unable to connect to ssl://gateway.push.apple.com:2195 ` I have searched this but didn't get resolved. Can u please guide why is this so?

**Comment by hasyapanchasara** [comment]
Hi, Check my code for php which send VOIP push notification.
Below is configuration based on development and production certificate you have created.

'ssl://gateway.push.apple.com:2195'
'ssl://gateway.sandbodx.push.apple.com:2195'

This should match to send a notificatin.

**Comment by Hamza123Imran** [comment]
Hi @hasyapanchasara  i have followed your steps and created pem file and than added on my server side but when i try to send notification it shows the above error, i have check the validation of pem file through this link, `http://apns-gcm.bryantan.info` which shows me that pem file is successfully valid. But i'm getting same error.

**Comment by hasyapanchasara** [comment]
Hi @Hamza123Imran. 

Hope you doing well.

About http://apns-gcm.bryantan.info, I am not much confident and aware, I have always used commands and simple push.php file given in my repository, and that works well. 

NWPusher also worked well https://github.com/noodlewerk/NWPusher. 

I suggest you to use manual commands and php code or NWPusher.

Regards.
